name: Esports-only props
on:
  workflow_dispatch: {}
  push:
    paths:
      - 'Esports'
      - 'esports_only.py'
      - '.github/workflows/esports.yml'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install pandas requests

      - name: Run base scraper
        run: |
          python - << 'PY'
          from underdog_scraper import UnderdogScraper
          UnderdogScraper().scrape()  # writes underdog_props.csv
          PY

      # If your esports file is named "Esports", change the next line to: python Esports
      - name: Filter to esports
        run: python esports_only.py

      - name: Upload esports-only CSV
        uses: actions/upload-artifact@v4
        with:
          name: underdog_props_esports
          path: underdog_props_esports.csv
