name: Run Underdog Scraper
on:
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests pandas

      - name: Run scraper (call class directly, no file edits)
        run: |
          python - << 'PY'
          from underdog_scraper import UnderdogScraper
          UnderdogScraper().scrape()
          PY

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: underdog_props
          path: underdog_props.csv
